project_id = "supabase-functions"

[functions.linear-to-slack]
enabled = true
verify_jwt = false
import_map = "./functions/linear-to-slack/deno.json"
entrypoint = "./functions/linear-to-slack/index.ts"
